import jsPDF from 'jspdf';

export const generatePDF = (lessonTitle: string = 'untitled', notes: string, summary: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const lineHeight = 6;
  let yPosition = margin;

  const addWrappedText = (text: string, x: number, y: number, maxWidth: number, fontSize: number = 12) => {
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, y);
    return y + (lines.length * lineHeight);
  };

  // Header
  doc.setFontSize(20);
  doc.setTextColor(37, 99, 235);
  doc.text('SkillMentor.AI - Study Notes', margin, yPosition);
  yPosition += 15;

  // Lesson Title
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  const safeTitle = lessonTitle || 'Untitled Lesson';
  yPosition = addWrappedText(`Lesson: ${safeTitle}`, margin, yPosition, pageWidth - 2 * margin, 16);
  yPosition += 10;

  // Date
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, yPosition);
  yPosition += 20;

  // Notes Section
  if (notes?.trim()) {
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('My Learning Notes', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(11);
    yPosition = addWrappedText(notes, margin, yPosition, pageWidth - 2 * margin, 11);
    yPosition += 15;
  }

  // Add new page if needed
  if (yPosition > pageHeight - 100) {
    doc.addPage();
    yPosition = margin;
  }

  // Summary Section
  if (summary?.trim()) {
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text('AI-Generated Summary', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    yPosition = addWrappedText(summary, margin, yPosition, pageWidth - 2 * margin, 11);
  }

  // Footer
  const footerY = pageHeight - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by SkillMentor.AI - Powered by Gemini AI', margin, footerY);

  // Safe filename generation
  const sanitizedTitle = (lessonTitle || 'untitled').replace(/[^a-z0-9]/gi, '_').toLowerCase();
  const filename = `skillmentor_notes_${sanitizedTitle}_${new Date().toISOString().split('T')[0]}.pdf`;

  doc.save(filename);
};
